{
 "title": "Crawler Application",
 "time": { "from": "2019-02-25T17:27:51.680Z", "to": "2019-02-25T20:40:00.515Z" },
 "templating": {
  "list": [
   {
    "name": "namespace",
    "label": "namespace",
    "query": "label_values(kubernetes_namespace)"
   }
  ]
 },
 "panels": [
  {
   "title": "User Interface - Requests rate per minute",
   "type": "graph",
   "gridPos": { "h": 6, "w": 8, "x": 0, "y": 0 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "rate(web_page_gen_time_count{kubernetes_namespace=\"$namespace\"}[1m])"
    }
   ]
  },
  {
   "title": "User Interface - Number of processed requests",
   "type": "graph",
   "gridPos": { "h": 6, "w": 7, "x": 8, "y": 0 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "web_pages_served{kubernetes_namespace=\"$namespace\"}",
     "legendFormat": "{{ instance }}"
    }
   ]
  },
  {
   "title": "User Interface - 95 percentile of a page generation time",
   "type": "graph",
   "gridPos": { "h": 6, "w": 9, "x": 15, "y": 0 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "histogram_quantile(0.95, sum(rate(web_page_gen_time_bucket{kubernetes_namespace=\"$namespace\"}[5m])) by (le))",
     "legendFormat": "$namespace"
    }
   ]
  },
  {
   "title": "Crawler - Number of parsed pages per minute",
   "type": "graph",
   "gridPos": { "h": 7, "w": 8, "x": 0, "y": 6 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "rate(crawler_pages_parsed{kubernetes_namespace=\"$namespace\"}[1m])"
    }
   ]
  },
  {
   "title": "Crawler - Connections counter",
   "type": "graph",
   "gridPos": { "h": 7, "w": 6, "x": 8, "y": 6 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "crawler_site_connection_time_count{kubernetes_namespace=\"$namespace\"}",
     "legendFormat": "{{ instance }} -- {{ kubernetes_namespace }}"
    }
   ]
  },
  {
   "title": "Crawler - 95 percentile of a parsing time",
   "type": "graph",
   "gridPos": { "h": 7, "w": 10, "x": 14, "y": 6 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "histogram_quantile(0.95, sum(rate(crawler_page_parse_time_bucket{kubernetes_namespace=\"$namespace\"}[5m])) by (le))",
     "legendFormat": "$namespace"
    }
   ]
  }
 ]
}